name: Action Workflow

on:
  repository_dispatch:
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  #  push:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          export PROJECT_NAME=$(basename $GITHUB_REPOSITORY)
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          echo $PROJECT_NAME
      #          git clone git@github:$GITHUB_REPOSITORY
      #          git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Mona the Octocat"
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
